version: "3.9"

services:
  storage-service:
    build: ./storage-service
    depends_on:
      - storage-db
      - storage-minio
    environment:
      - DB_HOST=storage-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=storage
      - MINIO_ENDPOINT=storage-minio:9000
      - MINIO_USER=storage
      - MINIO_PASSWORD=admin123
    restart: always
    networks:
      - backend

  storage-db:
    image: postgres:15
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - storage-db-data:/var/lib/postgresql/data
    networks:
      - backend

  storage-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: storage
      MINIO_ROOT_PASSWORD: admin123
    restart: always
    volumes:
      - storage-minio-data:/data
    ports:
      - "9001:9001"
    networks:
      - backend

  analysis-service:
    build: ./analysis-service
    depends_on:
      - analysis-db
      - analysis-minio
    environment:
      - DB_HOST=analysis-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=analysis
      - MINIO_ENDPOINT=analysis-minio:9000
    restart: always
    networks:
      - backend

  analysis-db:
    image: postgres:15
    environment:
      POSTGRES_DB: analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - analysis-db-data:/var/lib/postgresql/data
    networks:
      - backend

  analysis-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: analysis
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - analysis-minio-data:/data
    ports:
      - "9002:9001"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - storage-service
#     - analysis-service
    networks:
      - backend

volumes:
  storage-db-data:
  storage-minio-data:
  analysis-db-data:
  analysis-minio-data:

networks:
  backend:
