version: "3.9"

services:
  file-storage-service:
    build: ./file-storage-service
    depends_on:
      - storage-db
      - storage-minio
    environment:
      - DB_HOST=storage-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=storage
      - MINIO_ENDPOINT=http://storage-minio:9000
      - MINIO_USER=storage
      - MINIO_PASSWORD=admin
    networks:
      - backend

  storage-db:
    image: postgres:15
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - storage-db-data:/var/lib/postgresql/data
    networks:
      - backend

  storage-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: storage
      MINIO_ROOT_PASSWORD: admin
    volumes:
      - storage-minio-data:/data
    ports:
      - "9001:9001"
    networks:
      - backend

#  file-analysis-service:
#    build: ./file-analysis-service
#    depends_on:
#      - analysis-db
#      - analysis-minio
#    environment:
#      - DB_HOST=analysis-db
#      - DB_PORT=5432
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#      - DB_NAME=analysis
#      - MINIO_ENDPOINT=http://analysis-minio:9000
#    networks:
#      - backend
#
#  analysis-db:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: analysis
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - analysis-db-data:/var/lib/postgresql/data
#    networks:
#      - backend
#
#  analysis-minio:
#    image: minio/minio
#    command: server /data --console-address ":9002"
#    environment:
#      MINIO_ROOT_USER: minioadmin
#      MINIO_ROOT_PASSWORD: minioadmin
#    volumes:
#      - analysis-minio-data:/data
#    ports:
#      - "9002:9002"
#    networks:
#      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - file-storage-service
#      - file-analysis-service
    networks:
      - backend

volumes:
  storage-db-data:
  storage-minio-data:
#  analysis-db-data:
#  analysis-minio-data:

networks:
  backend:
